<?php

include_once '../../../includes/dbh.inc.php';
include_once '../../../includes/super_admin/create_account_view.inc.php';
include_once '../../../includes/SuperAdmin_model.inc.php';
include_once 'header.php';


$agreement = get_user_agreement($pdo, $_SESSION["account_id"]);
?>


<!--  Header End -->
<div class="container-fluid">
    <div class="container-fluid">
        <!-- BREADCRUMB -->
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active" aria-current="page">Add Account</li>
            </ol>
        </nav>

        <div class="card">
            <div class="card-body">

                <h2 class="fw-semibold mb-4 text-center">Create Account</h2>

                <div class="container">
                    <form method="post" action="../../../includes/super_admin/create_account.inc.php" id="createAccountForm" class="needs-validation" novalidate>

                        <div class="row">
                            <div class="col-12 col-md-12">
                                <?php
                                account_creation_success();
                                ?>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-12 col-md-4">
                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control" id="first_name" name="first_name" placeholder="name@example.com" maxlength="30" required>
                                    <label for="floatingInput1">First Name</label>
                                    <div class="invalid-feedback">First name is required</div>
                                </div>
                            </div>
                            <div class="col-12 col-md-4">
                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control" id="last_name" name="last_name" placeholder="name@example.com" maxlength="30" required>
                                    <label for="floatingInput2">Last Name</label>
                                    <div class="invalid-feedback">Last name is required</div>
                                </div>
                            </div>
                            <div class="col-12 col-md-4">
                                <select class="form-select form-select-md  rounded-1 p-3" name="role_description" id="role_description" aria-label="Role" required>
                                    <option value="" disabled selected>Role</option>
                                    <option value="admin">Admin</option>
                                    <option value="guard">Guard</option>
                                </select>
                                <div class="invalid-feedback">Role is required</div>
                                <div class="mb-3"></div>
                                <!-- just an additional space so the fields would be aligned -->
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 col-md-6">
                                <div class="form-floating mb-3">
                                    <input type="email" class="form-control" id="email" name="account_email" placeholder="name@example.com" maxlength="50" required>
                                    <label for="floatingInput1">Email Address</label>
                                    <div class="invalid-feedback" id="emailFeedback">Email is required</div>
                                </div>
                            </div>
                            <div class="col-12 col-md-6">
                                <div class="form-floating mb-3">
                                    <input type="text" class="form-control" id="number" name="account_number" placeholder="Phone Number" maxlength="11" required>
                                    <label for="number">Phone Number</label>
                                    <div class="invalid-feedback" id="numberFeedback">Phone number is required</div>
                                </div>
                            </div>
                        </div>
                        <!-- <div class="row">
                            <div class="col-12 col-md-12">
                                <div class="form-floating mb-2">
                                    <input type="password" class="form-control" id="floatingInput1" placeholder="name@example.com" value="12345678" readonly>
                                    <label for="floatingInput1">Password</label>
                                </div>
                                <i><small class="form-text text-muted"><b>Note:</b> Password is auto-generated by the system</small></i>
                            </div>
                        </div> -->

                        <div class="row mt-3">
                            <div class="col-12 col-md-6 offset-md-3 d-flex justify-content-center">
                                <button class="btn btn-primary p-3 w-50 mb-2" type="submit" disabled>Create</button>
                            </div>
                            <div class="col-12">
                                <?php
                                check_create_account_errors();
                                ?>
                            </div>
                        </div>

                    </form>
                </div>



            </div>
        </div>
    </div>
</div>



<div class="modal fade" id="termsModal" tabindex="-1" aria-labelledby="termsModalLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header d-flex flex-column align-items-center">
                <img src="../../images/logos/san_lorenzo_logo.svg" alt="Subdivision Logo" class="img-fluid mb-2" style="max-width: 100px;">
                <h3 class="modal-title text-center" id="termsModalLabel">Terms and Conditions</h3>
            </div>
            <div class="modal-body">
                <p class="text-primary text-justify">
                    As the Super Admin of the San Lorenzo Phase 1 Subdivision SeQRity system, you agree to the following terms and conditions to ensure the safety and privacy of admins' and guards' data:
                </p>
                <ul class="list-unstyled text-justify">
                    <li class="mb-2"><i class="bi bi-check-circle text-success"></i> The data collected, including personal information and other related details, will be used solely for the management and operation of the SeQRity system.</li>
                    <li class="mb-2"><i class="bi bi-check-circle text-success"></i> You are responsible for ensuring that all collected data is stored securely and protected from unauthorized access.</li>
                    <li class="mb-2"><i class="bi bi-check-circle text-success"></i> Under no circumstances will the data be shared with third parties without the explicit consent of the individuals concerned, except as required by law.</li>
                    <li class="mb-2"><i class="bi bi-check-circle text-success"></i> You will comply with all relevant data protection and privacy laws to maintain the confidentiality and integrity of the data.</li>
                    <li class="mb-2"><i class="bi bi-check-circle text-success"></i> In the event of a data breach or security incident, you must promptly notify the affected individuals and take appropriate measures to mitigate any potential harm.</li>
                </ul>
                <p class="text-primary text-justify">
                    By accepting these terms, you commit to upholding the highest standards of data security and privacy for the benefit of the admins and guards of San Lorenzo Phase 1 Subdivision.
                </p>
            </div>
            <div class="modal-footer">
                <a href="../../../includes/logout.inc.php"><button type="button" class="btn btn-light">I Disagree (Log Out)</button></a>
                <form id="agreeForm" action="../../../includes/super_admin/terms.inc.php" method="POST" style="display: inline;">
                    <button type="submit" class="btn btn-primary">I Agree</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- shows the agreement modal when user hasnt agreed to the terms and conditions -->
<script>
    // Check agreement status here
    <?php if ($agreement == 0) : ?>
        $(document).ready(function() {
            $('#termsModal').modal('show');
        });
    <?php endif; ?>
</script>

<script src="../../js/create_account.js"></script>

<?php
include_once 'footer.php';
?>